/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package public_pages;

import admin_pages.ManageBranchesView;

/**
 *
 * @author Kein
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeLogin
     */
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminLogin = new javax.swing.JLabel();
        panAdminLoginForm = new javax.swing.JPanel();
        btnAdminLogIn = new javax.swing.JButton();
        btnAdminGoToAddTransactionForm = new javax.swing.JButton();
        lblAdminLoginEmailAddress = new javax.swing.JLabel();
        lblAdminLoginPassword = new javax.swing.JLabel();
        txtAdminLoginEmailAddress = new javax.swing.JTextField();
        txtAdminLoginPassword = new javax.swing.JTextField();
        btnLogInAsEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Login");
        setResizable(false);

        lblAdminLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAdminLogin.setText("Admin Login");

        panAdminLoginForm.setBackground(java.awt.SystemColor.controlHighlight);

        btnAdminLogIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdminLogIn.setText("Log In");
        btnAdminLogIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdminLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLogInActionPerformed(evt);
            }
        });

        btnAdminGoToAddTransactionForm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdminGoToAddTransactionForm.setText("Go to Add Transaction Form");
        btnAdminGoToAddTransactionForm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdminGoToAddTransactionForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminGoToAddTransactionFormActionPerformed(evt);
            }
        });

        lblAdminLoginEmailAddress.setText("Email Address:");

        lblAdminLoginPassword.setText("Password:");

        btnLogInAsEmployee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogInAsEmployee.setText("Log in as Employee");
        btnLogInAsEmployee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogInAsEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInAsEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panAdminLoginFormLayout = new javax.swing.GroupLayout(panAdminLoginForm);
        panAdminLoginForm.setLayout(panAdminLoginFormLayout);
        panAdminLoginFormLayout.setHorizontalGroup(
            panAdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminLoginFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panAdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnAdminGoToAddTransactionForm)
                        .addComponent(btnAdminLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogInAsEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAdminLoginFormLayout.createSequentialGroup()
                        .addGroup(panAdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdminLoginEmailAddress)
                            .addComponent(lblAdminLoginPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panAdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdminLoginPassword)
                            .addComponent(txtAdminLoginEmailAddress))))
                .addGap(26, 26, 26))
        );

        panAdminLoginFormLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdminGoToAddTransactionForm, btnAdminLogIn, btnLogInAsEmployee});

        panAdminLoginFormLayout.setVerticalGroup(
            panAdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAdminLoginFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panAdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminLoginEmailAddress)
                    .addComponent(txtAdminLoginEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panAdminLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminLoginPassword)
                    .addComponent(txtAdminLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnAdminLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdminGoToAddTransactionForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogInAsEmployee)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblAdminLogin)
                    .addComponent(panAdminLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAdminLogin)
                .addGap(26, 26, 26)
                .addComponent(panAdminLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLogInActionPerformed
        ManageBranchesView manageEmployeesView = new ManageBranchesView();
        manageEmployeesView.setLocationRelativeTo(null);
        manageEmployeesView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminLogInActionPerformed

    private void btnAdminGoToAddTransactionFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminGoToAddTransactionFormActionPerformed
        AddTransactionForm addTransactionForm = new AddTransactionForm();
        addTransactionForm.setLocationRelativeTo(null);
        addTransactionForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminGoToAddTransactionFormActionPerformed

    private void btnLogInAsEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInAsEmployeeActionPerformed
        EmployeeLogin employeeLogin = new EmployeeLogin();
        employeeLogin.setLocationRelativeTo(null);
        employeeLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogInAsEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminGoToAddTransactionForm;
    private javax.swing.JButton btnAdminLogIn;
    private javax.swing.JButton btnLogInAsEmployee;
    private javax.swing.JLabel lblAdminLogin;
    private javax.swing.JLabel lblAdminLoginEmailAddress;
    private javax.swing.JLabel lblAdminLoginPassword;
    private javax.swing.JPanel panAdminLoginForm;
    private javax.swing.JTextField txtAdminLoginEmailAddress;
    private javax.swing.JTextField txtAdminLoginPassword;
    // End of variables declaration//GEN-END:variables
}
