/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package public_pages;

import employee_pages.ManageTransactionsView;

/**
 *
 * @author Kein
 */
public class EmployeeLogin extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeLogin
     */
    public EmployeeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployeeLogin = new javax.swing.JLabel();
        panEmployeeLoginForm = new javax.swing.JPanel();
        btnEmployeeLogIn = new javax.swing.JButton();
        btnEmployeeGoToAddTransactionForm = new javax.swing.JButton();
        lblEmployeeLoginEmailAddress = new javax.swing.JLabel();
        lblEmployeeLoginPassword = new javax.swing.JLabel();
        txtEmployeeLoginEmailAddress = new javax.swing.JTextField();
        txtEmployeeLoginPassword = new javax.swing.JTextField();
        btnLogInAsAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Login");
        setResizable(false);

        lblEmployeeLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmployeeLogin.setText("Employee Login");

        panEmployeeLoginForm.setBackground(java.awt.SystemColor.controlHighlight);

        btnEmployeeLogIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmployeeLogIn.setText("Log In");
        btnEmployeeLogIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmployeeLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeLogInActionPerformed(evt);
            }
        });

        btnEmployeeGoToAddTransactionForm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEmployeeGoToAddTransactionForm.setText("Go to Add Transaction Form");
        btnEmployeeGoToAddTransactionForm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmployeeGoToAddTransactionForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeGoToAddTransactionFormActionPerformed(evt);
            }
        });

        lblEmployeeLoginEmailAddress.setText("Email Address:");

        lblEmployeeLoginPassword.setText("Password:");

        btnLogInAsAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogInAsAdmin.setText("Log in as Admin");
        btnLogInAsAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogInAsAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInAsAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panEmployeeLoginFormLayout = new javax.swing.GroupLayout(panEmployeeLoginForm);
        panEmployeeLoginForm.setLayout(panEmployeeLoginFormLayout);
        panEmployeeLoginFormLayout.setHorizontalGroup(
            panEmployeeLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmployeeLoginFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panEmployeeLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEmployeeLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnEmployeeGoToAddTransactionForm)
                        .addComponent(btnEmployeeLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogInAsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panEmployeeLoginFormLayout.createSequentialGroup()
                        .addGroup(panEmployeeLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmployeeLoginEmailAddress)
                            .addComponent(lblEmployeeLoginPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panEmployeeLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmployeeLoginPassword)
                            .addComponent(txtEmployeeLoginEmailAddress))))
                .addGap(26, 26, 26))
        );

        panEmployeeLoginFormLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEmployeeGoToAddTransactionForm, btnEmployeeLogIn, btnLogInAsAdmin});

        panEmployeeLoginFormLayout.setVerticalGroup(
            panEmployeeLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmployeeLoginFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panEmployeeLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeLoginEmailAddress)
                    .addComponent(txtEmployeeLoginEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panEmployeeLoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeLoginPassword)
                    .addComponent(txtEmployeeLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnEmployeeLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmployeeGoToAddTransactionForm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogInAsAdmin)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEmployeeLogin)
                    .addComponent(panEmployeeLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblEmployeeLogin)
                .addGap(26, 26, 26)
                .addComponent(panEmployeeLoginForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeLogInActionPerformed
        ManageTransactionsView manageTransactionsView = new ManageTransactionsView();
        manageTransactionsView.setLocationRelativeTo(null);
        manageTransactionsView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeLogInActionPerformed

    private void btnEmployeeGoToAddTransactionFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeGoToAddTransactionFormActionPerformed
        AddTransactionForm addTransactionForm = new AddTransactionForm();
        addTransactionForm.setLocationRelativeTo(null);
        addTransactionForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeGoToAddTransactionFormActionPerformed

    private void btnLogInAsAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInAsAdminActionPerformed
        AdminLogin adminLogin = new AdminLogin();
        adminLogin.setLocationRelativeTo(null);
        adminLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogInAsAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmployeeGoToAddTransactionForm;
    private javax.swing.JButton btnEmployeeLogIn;
    private javax.swing.JButton btnLogInAsAdmin;
    private javax.swing.JLabel lblEmployeeLogin;
    private javax.swing.JLabel lblEmployeeLoginEmailAddress;
    private javax.swing.JLabel lblEmployeeLoginPassword;
    private javax.swing.JPanel panEmployeeLoginForm;
    private javax.swing.JTextField txtEmployeeLoginEmailAddress;
    private javax.swing.JTextField txtEmployeeLoginPassword;
    // End of variables declaration//GEN-END:variables
}
